server {
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/brainskool-api.softvibes.art/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/brainskool-api.softvibes.art/privkey.pem;
    server_name brainskool-api.softvibes.art;
    location ^~ /.well-known/acme-challenge/ { root /var/www/skool-guide-acme; }
    location / {
        proxy_pass http://127.0.0.1:4651;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_read_timeout 200s;
        client_max_body_size 8k;
    }
}

server {
 listen 80;
 server_name brainskool-api.softvibes.art;
 location ^~ /.well-known/acme-challenge/ { root /var/www/skool-guide-acme; }
 location / { return 301 https://$host$request_uri; }
}
