export function mountGuide({navigate,currentNode,hasNode}) {
  const endpoint=document.querySelector('meta[name="guide-api"]')?.content;
  if(!endpoint)return;
  const launch=document.createElement('button');launch.className='guide-launch';launch.type='button';launch.textContent='✦ Pregúntale al experto';launch.setAttribute('aria-expanded','false');launch.setAttribute('aria-controls','skool-guide');document.body.append(launch);
  const panel=document.createElement('section');panel.id='skool-guide';panel.className='guide-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Skool Guide');
  panel.innerHTML='<header><div><strong>Skool Guide</strong><small>Tu guía en el cerebro · Hermes</small></div><button type="button" class="guide-close" aria-label="Cerrar chat">×</button></header><div class="guide-context"></div><div class="guide-messages" role="log" aria-live="polite" aria-label="Conversación"></div><p class="guide-status" role="status"></p><form><label class="guide-sr" for="guide-input">Tu pregunta</label><textarea id="guide-input" placeholder="¿Qué quieres conseguir con tu agencia?" maxlength="2000" rows="2" required></textarea><button type="submit">Enviar</button></form><small class="guide-note">Respuestas basadas en las lecciones. Verifica las fuentes.</small>';
  document.body.append(panel);
  const log=panel.querySelector('.guide-messages'),input=panel.querySelector('textarea'),form=panel.querySelector('form'),status=panel.querySelector('.guide-status'),context=panel.querySelector('.guide-context'),submit=form.querySelector('button');let busy=false;
  function bubble(text,role='assistant'){const el=document.createElement('div');el.className='guide-message '+role;el.textContent=text;log.append(el);log.scrollTop=log.scrollHeight;return el;}
  bubble('Hola, soy Skool Guide. Cuéntame qué quieres mejorar y te ayudaré a encontrar la lección y el siguiente paso.');
  const suggestions=document.createElement('div');suggestions.className='guide-suggestions';for(const text of ['¿Cómo atraer leads con intención de compra?','Ayúdame a mejorar mi oferta']){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=()=>{input.value=text;form.requestSubmit();};suggestions.append(b);}log.append(suggestions);
  function open(){panel.hidden=false;launch.setAttribute('aria-expanded','true');const n=currentNode();context.textContent=n?'Estás explorando: '+n.title:'Explorando toda la biblioteca';input.focus();}
  function close(){panel.hidden=true;launch.setAttribute('aria-expanded','false');launch.focus();}
  launch.onclick=()=>panel.hidden?open():close();panel.querySelector('.guide-close').onclick=close;
  panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}});
  input.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();return;}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit();}});
  function result(data){bubble(data.answer);for(const card of data.recommendations||[]){if(!hasNode(card.node_id))continue;const box=document.createElement('article');box.className='guide-card';const title=document.createElement('strong');title.textContent=card.title;const why=document.createElement('p');why.textContent=card.reason;const source=document.createElement('small');source.textContent=(card.evidence||[]).map(x=>x.source+(x.timestamp?' · '+x.timestamp:'')).join(' | ');const link=document.createElement('a');link.href='?node='+encodeURIComponent(card.node_id);link.textContent='Ir al nodo →';link.onclick=e=>{e.preventDefault();navigate(card.node_id);close();};box.append(title,why,source,link);log.append(box);}log.scrollTop=log.scrollHeight;}
  form.onsubmit=async e=>{e.preventDefault();const message=input.value.trim();if(!message||busy)return;busy=true;submit.disabled=true;input.value='';suggestions.hidden=true;bubble(message,'user');status.textContent='Conectando con Hermes…';const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),200000);
    try{const response=await fetch(endpoint+'/chat',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,node_id:currentNode()?.id||null}),signal:abort.signal});if(!response.ok){let data={};try{data=await response.json();}catch{}throw Error(data.error||'Servicio no disponible. Inténtalo de nuevo.');}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',completed=false;
      while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let pos;while((pos=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,pos);buffer=buffer.slice(pos+2);const kind=frame.split('\n').find(x=>x.startsWith('event: '))?.slice(7);const raw=frame.split('\n').filter(x=>x.startsWith('data: ')).map(x=>x.slice(6)).join('\n');if(!raw)continue;const data=JSON.parse(raw);if(kind==='status')status.textContent=data.message;if(kind==='result'){result(data);completed=true;}if(kind==='error')throw Error(data.message);}if(done)break;}if(!completed)throw Error('La conexión terminó antes de recibir la respuesta. Inténtalo de nuevo.');status.textContent='';
    }catch(error){status.textContent=error.name==='AbortError'?'La consulta tardó demasiado. Inténtalo de nuevo.':error.message;input.value=message;}finally{clearTimeout(timer);busy=false;submit.disabled=false;}
  };
}
